#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"
# ~/.huskyrc
# This loads nvm.sh and sets the correct PATH before running hook
# SPECIFY Location of your node installation folder default: .nvm in my case .config/nvm
export NVM_DIR="$HOME/.config/nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
yarn build
